FROM node:18.14.1-alpine as build

ARG REACT_APP_NAME
ENV REACT_APP_NAME=$REACT_APP_NAME
ARG REACT_APP_SOCKET_SERVER
ENV REACT_APP_SOCKET_SERVER=$REACT_APP_SOCKET_SERVER
ARG REACT_APP_END_POINT
ENV REACT_APP_END_POINT=$REACT_APP_END_POINT
ARG REACT_APP_END_POINT_TOURNAMENT
ENV REACT_APP_END_POINT_TOURNAMENT=$REACT_APP_END_POINT_TOURNAMENT
ARG REACT_APP_END_POINT_PVP_BOT
ENV REACT_APP_END_POINT_PVP_BOT=$REACT_APP_END_POINT_PVP_BOT
ARG REACT_APP_URL_DOMAIN
ENV REACT_APP_URL_DOMAIN=$REACT_APP_URL_DOMAIN
ARG REACT_APP_TYPE_APP
ENV REACT_APP_TYPE_APP=$REACT_APP_TYPE_APP
ARG REACT_APP_ENV
ENV REACT_APP_ENV=$REACT_APP_ENV
ARG REACT_APP_STREAMING_ASSET_URL
ENV REACT_APP_STREAMING_ASSET_URL=$REACT_APP_STREAMING_ASSET_URL
ARG REACT_APP_API_ADMIN_URL
ENV REACT_APP_API_ADMIN_URL=$REACT_APP_API_ADMIN_URL

WORKDIR /app
COPY package.json ./
#COPY package-lock.json ./
RUN npm i --legacy-peer-deps
COPY ./ ./

RUN npm run build

FROM nginx:1.16.0-alpine
COPY --from=build /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d

CMD ["nginx", "-g", "daemon off;"]
